services:
  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.4
    container_name: chroma
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: "no"

  ragchat:
    build:
      context: .
    container_name: ragchat
    ports:
      - "8080:8080"
    depends_on:
      - chroma
    environment:
      CHROMA_HOST: chroma
      CHROMA_PORT: 8000
      OLLAMA_SERVICE_URL: http://host.docker.internal:11434
    volumes:
      - "D:/LLM/models/ONNX:/app/ONNX:ro"
      - "D:/Projets/data:/app/knowledge_bases:ro"